# .github/aerospike/aerospike.conf
service {
    # This prevents the server from stopping writes due to low system memory
    stop-writes-sys-memory-pct 100 
}

network {
    service {
        address any
        port 3000
    }
}

namespace test_set {
    replication-factor 1
    memory-size 1G
    storage-engine memory
    
    # Ensure TTLs are allowed
    allow-ttl true
    # Prevent eviction from stopping tests
    nsup-period 15
}