version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
  - package-ecosystem: "nuget"
    directory: "/src/AeroSharp"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
